const systemData = [
    { "Name": "Fees Collection", "Action": true },
    { "Name": "Income", "Action": false },
    { "Name": "Expense", "Action": true },
    { "Name": "Student Attendance", "Action": false },
    { "Name": "Examination", "Action": true },
    { "Name": "Download Center", "Action": false },
    { "Name": "Library", "Action": true },
    { "Name": "Inventory", "Action": false },
    { "Name": "Transport", "Action": true },
    { "Name": "Hostel", "Action": false },
    { "Name": "Communicate", "Action": true },
    { "Name": "Front CMS", "Action": false },
    { "Name": "Front Office", "Action": true },
    { "Name": "Homework", "Action": false },
    { "Name": "Certificate", "Action": true },
    { "Name": "Calendar To Do List", "Action": false },
    { "Name": "Online Examination", "Action": true },
    { "Name": "Chat", "Action": false },
    { "Name": "Multi Class", "Action": true },
    { "Name": "Online Admission", "Action": false },
    { "Name": "Alumni", "Action": true },
    { "Name": "Lesson Plan", "Action": false },
    { "Name": "Annual Calendar", "Action": true },
    { "Name": "Student CV", "Action": false },
    { "Name": "Zoom Live Classes", "Action": true },
    { "Name": "Gmeet Live Classes", "Action": false },
    { "Name": "Online Course", "Action": true },
    { "Name": "Behaviour Records", "Action": false },
    { "Name": "CBSE Examination", "Action": true },
    { "Name": "Multi Branch", "Action": false },
    { "Name": "Two Factor Authenticator", "Action": true },
    { "Name": "QR Code Attendence", "Action": false },
    { "Name": "Quick Fees", "Action": true },
    { "Name": "Thermal Print", "Action": false }
  ]

  export default systemData;
  