const studentData=[
    {
      "class": "Class 1-A",
      "admission_no": "120020",
      "student_name": "Ashwani Kumar",
      "fees_group": [
        "Class 1 General (April Month Fees : apr-month-fees)",
        "Class 1 General (May Month Fees : may-month-fees)",
        "Class 1 General (June Month Fees : jun-month-fees)",
        "Class 1 General (July Month Fees : jul-month-fees)",
        "Class 1 General (August Month Fees : aug-month-fees)",
        "Class 1 General (Bus-fees : Bus-fees)",
        "Class 1 General (Exam Fees : Exam)",
        "Class 1 General (September Month Fees : sep-month-fees)",
        "Class 1 General (October Month Fees : oct-month-fees)",
        "Class 1 General (November Month Fees : nov-month-fees)",
        "Class 1 General (December Month Fees : dec-month-fees)",
        "Class 1 General (January Month Fees : jan-month-fees)",
        "Class 1 General (February Month Fees : feb-month-fees)",
        "Class 1 General (March Month Fees : march-month-fees)",
        "Class 1 Lump Sum (Lumpsum fees : lumpsum-fees)",
        "Class 1- I Installment (April Month Fees : apr-month-fees)",
        "(Transport Fees : May)",
        "(Transport Fees : June)",
        "(Transport Fees : July)",
        "(Transport Fees : August)",
        "(Transport Fees : September)",
        "(Transport Fees : October)",
        "(Transport Fees : November)",
        "(Transport Fees : December)",
        "(Transport Fees : January)",
        "(Transport Fees : February)",
        "(Transport Fees : March)"
      ],
      "amount": 5350.00,
      "paid": 200.00,
      "discount": 0.00,
      "fine": 0.00,
      "balance": 5150.00
    },
    {
      "class": "Class 1-B",
      "admission_no": "120028",
      "student_name": "Nishant Sindhu",
      "fees_group": [
        "Class 1 General (Admission Fees : admission-fees)",
        "Class 1 General (April Month Fees : apr-month-fees)",
        "Class 1 General (May Month Fees : may-month-fees)",
        "Class 1 General (June Month Fees : jun-month-fees)",
        "Class 1 General (July Month Fees : jul-month-fees)",
        "Class 1 General (August Month Fees : aug-month-fees)",
        "Class 1 General (Bus-fees : Bus-fees)",
        "Class 1 General (Exam Fees : Exam)",
        "Class 1 General (September Month Fees : sep-month-fees)",
        "Class 1 General (October Month Fees : oct-month-fees)",
        "Class 1 General (November Month Fees : nov-month-fees)",
        "Class 1 General (December Month Fees : dec-month-fees)",
        "Class 1 General (January Month Fees : jan-month-fees)",
        "Class 1 General (February Month Fees : feb-month-fees)",
        "Class 1 General (March Month Fees : march-month-fees)",
        "Class 1 Lump Sum (Lumpsum fees : lumpsum-fees)",
        "Class 1- I Installment (April Month Fees : apr-month-fees)",
        "(Transport Fees : April)",
        "(Transport Fees : June)",
        "(Transport Fees : July)",
        "(Transport Fees : August)",
        "(Transport Fees : September)",
        "(Transport Fees : October)",
        "(Transport Fees : November)",
        "(Transport Fees : December)",
        "(Transport Fees : January)",
        "(Transport Fees : February)",
        "(Transport Fees : March)"
      ],
      "amount": 7850.00,
      "paid": 0.00,
      "discount": 0.00,
      "fine": 0.00,
      "balance": 7850.00
    },
    {
      "class": "Class 1-A",
      "admission_no": "120039",
      "student_name": "Nathan Smith",
      "fees_group": [
        "Class 1 General (Admission Fees : admission-fees)",
        "Class 1 General (May Month Fees : may-month-fees)",
        "Class 1 General (June Month Fees : jun-month-fees)",
        "Class 1 General (July Month Fees : jul-month-fees)",
        "Class 1 General (August Month Fees : aug-month-fees)",
        "Class 1 General (Bus-fees : Bus-fees)",
        "Class 1 General (Exam Fees : Exam)",
        "Class 1 General (September Month Fees : sep-month-fees)",
        "Class 1 General (October Month Fees : oct-month-fees)",
        "Class 1 General (November Month Fees : nov-month-fees)",
        "Class 1 General (December Month Fees : dec-month-fees)",
        "Class 1 General (January Month Fees : jan-month-fees)",
        "Class 1 General (February Month Fees : feb-month-fees)",
        "Class 1 General (March Month Fees : march-month-fees)",
        "Class 1 Lump Sum (Lumpsum fees : lumpsum-fees)",
        "Class 1- I Installment (April Month Fees : apr-month-fees)",
        "(Transport Fees : April)",
        "(Transport Fees : June)",
        "(Transport Fees : July)",
        "(Transport Fees : August)",
        "(Transport Fees : September)",
        "(Transport Fees : October)",
        "(Transport Fees : November)",
        "(Transport Fees : December)",
        "(Transport Fees : January)",
        "(Transport Fees : February)",
        "(Transport Fees : March)"
      ],
      "amount": 8050.00,
      "paid": 0.00,
      "discount": 0.00,
      "fine": 0.00,
      "balance": 8050.00
    },
    {
        "class": "Class 3-B",
        "admission_no": "0202",
        "student_name": "Emma Thomas",
        "fees_group": [
          "Class 3 General (Admission Fees : admission-fees)",
          "Class 3 General (April Month Fees : apr-month-fees)",
          "Class 3 General (May Month Fees : may-month-fees)",
          "Class 3 General (June Month Fees : jun-month-fees)",
          "Class 3 General (July Month Fees : jul-month-fees)",
          "Class 3 General (August Month Fees : aug-month-fees)",
          "Class 3 General (September Month Fees : sep-month-fees)",
          "Class 3 General (October Month Fees : oct-month-fees)",
          "Class 3 General (November Month Fees : nov-month-fees)",
          "Class 3 General (December Month Fees : dec-month-fees)",
          "Class 3 General (January Month Fees : jan-month-fees)",
          "Class 3 General (February Month Fees : feb-month-fees)",
          "Class 3 General (March Month Fees : march-month-fees)",
          "Exam (Exam Fees : exam-fees)",
          "Transport Fees : April", "May", "August", "September", "October", "November", "December", "January", "February", "March"
        ],
        "amount": 8550,
        "paid": 0,
        "discount": 0,
        "fine": 0,
        "balance": 8550
      },
      {
        "class": "Class 3-A",
        "admission_no": "03321",
        "student_name": "John M. Pinto",
        "fees_group": [
          "Class 3 General (Admission Fees : admission-fees)",
          "Class 3 General (May Month Fees : may-month-fees)",
          "Class 3 General (June Month Fees : jun-month-fees)",
          "Class 3 General (July Month Fees : jul-month-fees)",
          "Class 3 General (August Month Fees : aug-month-fees)",
          "Class 3 General (September Month Fees : sep-month-fees)",
          "Class 3 General (October Month Fees : oct-month-fees)",
          "Class 3 General (November Month Fees : nov-month-fees)",
          "Class 3 General (December Month Fees : dec-month-fees)",
          "Class 3 General (January Month Fees : jan-month-fees)",
          "Class 3 General (February Month Fees : feb-month-fees)",
          "Class 3 General (March Month Fees : march-month-fees)",
          "Exam (Exam Fees : exam-fees)",
          "Transport Fees : April", "May", "June", "July", "August", "September", "October", "November", "December", "January", "February", "March"
        ],
        "amount": 8250,
        "paid": 2000,
        "discount": 500,
        "fine": 0,
        "balance": 5750
      },
      {
        "class": "Class 3-A",
        "admission_no": "12003",
        "student_name": "Jasaon Martin",
        "fees_group": [
          "Class 3 General (Admission Fees : admission-fees)",
          "Class 3 General (April Month Fees : apr-month-fees)",
          "Class 3 General (May Month Fees : may-month-fees)",
          "Class 3 General (June Month Fees : jun-month-fees)",
          "Class 3 General (July Month Fees : jul-month-fees)",
          "Class 3 General (August Month Fees : aug-month-fees)",
          "Class 3 General (September Month Fees : sep-month-fees)",
          "Class 3 General (October Month Fees : oct-month-fees)",
          "Class 3 General (November Month Fees : nov-month-fees)",
          "Class 3 General (December Month Fees : dec-month-fees)",
          "Class 3 General (January Month Fees : jan-month-fees)",
          "Class 3 General (February Month Fees : feb-month-fees)",
          "Class 3 General (March Month Fees : march-month-fees)",
          "Exam (Exam Fees : exam-fees)",
          "Transport Fees : April", "May", "June", "July", "August", "September", "October", "January", "February", "March"
        ],
        "amount": 9050,
        "paid": 0,
        "discount": 0,
        "fine": 0,
        "balance": 9050
      },
      {
        "class": "Class 4-A",
        "admission_no": "18008",
        "student_name": "David Heart",
        "fees_group": [
          "Class 4 General (Admission Fees : admission-fees)",
          "Class 4 General (April Month Fees : apr-month-fees)",
          "Class 4 General (May Month Fees : may-month-fees)",
          "Class 4 General (June Month Fees : jun-month-fees)",
          "Class 4 General (July Month Fees : jul-month-fees)",
          "Class 4 General (August Month Fees : aug-month-fees)",
          "Class 4 General (September Month Fees : sep-month-fees)",
          "Class 4 General (October Month Fees : oct-month-fees)",
          "Class 4 General (November Month Fees : nov-month-fees)",
          "Class 4 General (December Month Fees : dec-month-fees)",
          "Class 4 General (January Month Fees : jan-month-fees)",
          "Class 4 General (February Month Fees : feb-month-fees)",
          "Class 4 General (March Month Fees : march-month-fees)",
          "Exam (Exam Fees : exam-fees)",
          "Transport Fees : April", "May", "June", "July", "October", "November", "December", "February", "March"
        ],
        "amount": 9600,
        "paid": 0,
        "discount": 0,
        "fine": 0,
        "balance": 9600
      },
      {
        "class": "Class 4-A",
        "admission_no": "11025",
        "student_name": "Surya Lalwani",
        "fees_group": [
          "Class 4 General (Admission Fees : admission-fees)",
          "Class 4 General (April Month Fees : apr-month-fees)",
          "Class 4 General (May Month Fees : may-month-fees)",
          "Class 4 General (June Month Fees : jun-month-fees)",
          "Class 4 General (July Month Fees : jul-month-fees)",
          "Class 4 General (August Month Fees : aug-month-fees)",
          "Class 4 General (September Month Fees : sep-month-fees)",
          "Class 4 General (October Month Fees : oct-month-fees)",
          "Class 4 General (November Month Fees : nov-month-fees)",
          "Class 4 General (December Month Fees : dec-month-fees)",
          "Class 4 General (January Month Fees : jan-month-fees)",
          "Class 4 General (February Month Fees : feb-month-fees)",
          "Class 4 General (March Month Fees : march-month-fees)",
          "Exam (Exam Fees : exam-fees)",
          "Transport Fees : April", "May", "June", "July", "August", "September", "October", "November", "December", "January", "February", "March"
        ],
        "amount": 9750,
        "paid": 2500,
        "discount": 600,
        "fine": 0,
        "balance": 6650
      },
      {
        "class": "Class 4-C",
        "admission_no": "18028",
        "student_name": "Rahul Sinha",
        "fees_group": [
          "Class 4 General (Admission Fees : admission-fees)",
          "Class 4 General (April Month Fees : apr-month-fees)",
          "Class 4 General (May Month Fees : may-month-fees)",
          "Class 4 General (June Month Fees : jun-month-fees)",
          "Class 4 General (July Month Fees : jul-month-fees)",
          "Class 4 General (August Month Fees : aug-month-fees)",
          "Class 4 General (September Month Fees : sep-month-fees)",
          "Class 4 General (October Month Fees : oct-month-fees)",
          "Class 4 General (November Month Fees : nov-month-fees)",
          "Class 4 General (December Month Fees : dec-month-fees)",
          "Class 4 General (January Month Fees : jan-month-fees)",
          "Class 4 General (February Month Fees : feb-month-fees)",
          "Class 4 General (March Month Fees : march-month-fees)",
          "Exam (Exam Fees : exam-fees)"
        ],
        "amount": 9150,
        "paid": 0,
        "discount": 0,
        "fine": 0,
        "balance": 9150
      }
  ]

  export default studentData;