const systemData=[
    { "name": "Weight", "action": true },
    { "name": "Upload Documents", "action": false },
    { "name": "Student Photo", "action": true },
    { "name": "RTE", "action": false },
    { "name": "Route List", "action": true },
    { "name": "Roll Number", "action": false },
    { "name": "Religion", "action": true },
    { "name": "Previous School Details", "action": false },
    { "name": "Note", "action": true },
    { "name": "National Identification Number", "action": false },
    { "name": "Mother Photo", "action": true },
    { "name": "Mother Phone", "action": false },
    { "name": "Mother Occupation", "action": true },
    { "name": "Mother Name", "action": false },
    { "name": "Mobile Number", "action": true },
    { "name": "Middle Name", "action": false },
    { "name": "Measurement Date", "action": true },
    { "name": "Local Identification Number", "action": false },
    { "name": "Last Name", "action": true },
    { "name": "IFSC Code", "action": false },
    { "name": "If Permanent Address Is Current Address", "action": true },
    { "name": "If Guardian Address Is Current Address", "action": false },
    { "name": "House", "action": true },
    { "name": "Hostel Details", "action": false },
    { "name": "Height", "action": true },
    { "name": "Guardian Relation", "action": false },
    { "name": "Guardian Photo", "action": true },
    { "name": "Guardian Phone", "action": false },
    { "name": "Guardian Occupation", "action": true },
    { "name": "Guardian Name", "action": false },
    { "name": "Guardian Email", "action": true },
    { "name": "Guardian Address", "action": false },
    { "name": "Father Photo", "action": true },
    { "name": "Father Phone", "action": false },
    { "name": "Father Occupation", "action": true },
    { "name": "Father Name", "action": false },
    { "name": "Email", "action": true },
    { "name": "Category", "action": false },
    { "name": "Caste", "action": true },
    { "name": "Blood Group", "action": false },
    { "name": "Barcode", "action": true },
    { "name": "Bank Name", "action": false },
    { "name": "Bank Account Number", "action": true },
    { "name": "Admission Date", "action": false }
  ]
  
  export default systemData;