const class4Data = [
    {
      id: '11011',
      name: 'MANISH RAJPUT',
      rollNo: '78768',
      class: 'Class 4(A)',
      fatherName: 'Lokesh',
      dob: '12/28/2009',
      gender: 'Male',
      category: '',
      mobileNumber: '9658471232',
      localId: '',
      guardianPhone: '',
      address: '',
      photo: ''
    },
    {
      id: '11025',
      name: 'Surya Lalwani',
      rollNo: '134',
      class: 'Class 4(A)',
      fatherName: 'James Stark',
      dob: '04/15/2015',
      gender: 'Male',
      category: '',
      mobileNumber: '97567987987',
      localId: '',
      guardianPhone: '',
      address: '',
      photo: ''
    },
    {
      id: '1121',
      name: 'sumit soni',
      rollNo: '13135',
      class: 'Class 4(A)',
      fatherName: 'sumita soni',
      dob: '03/17/2023',
      gender: 'Male',
      category: 'OBC',
      mobileNumber: '',
      localId: '',
      guardianPhone: '',
      address: '',
      photo: ''
    },
    {
      id: '12535',
      name: 'gaurav soni',
      rollNo: '154',
      class: 'Class 4(D)',
      fatherName: 'gauri',
      dob: '03/16/2023',
      gender: 'Male',
      category: 'General',
      mobileNumber: '',
      localId: '',
      guardianPhone: '',
      address: '',
      photo: ''
    },
    {
      id: '18008',
      name: 'David Heart',
      rollNo: '108',
      class: 'Class 4(A)',
      fatherName: 'Glenn Heart',
      dob: '03/18/2015',
      gender: 'Male',
      category: 'General',
      mobileNumber: '646445641654',
      localId: '',
      guardianPhone: '',
      address: '',
      photo: ''
    },
    {
      id: '18020',
      name: 'Jhony Taylor',
      rollNo: '12032',
      class: 'Class 4(B)',
      fatherName: 'Paul',
      dob: '06/04/2014',
      gender: 'Male',
      category: 'General',
      mobileNumber: '87978567',
      localId: '',
      guardianPhone: '',
      address: '',
      photo: ''
    },
    {
      id: '18021',
      name: 'Mohit Raina',
      rollNo: '',
      class: 'Class 4(A)',
      fatherName: 'Ravi Raina',
      dob: '06/16/2010',
      gender: 'Male',
      category: 'General',
      mobileNumber: '789412305',
      localId: '',
      guardianPhone: '',
      address: '',
      photo: ''
    },
    {
      id: '18028',
      name: 'Rahul Sinha',
      rollNo: '215',
      class: 'Class 4(C)',
      fatherName: 'B S SINHA',
      dob: '02/09/1999',
      gender: 'Male',
      category: '',
      mobileNumber: '7896541230',
      localId: '',
      guardianPhone: '',
      address: '',
      photo: ''
    },
    {
      id: '18087',
      name: 'Rohit Khanna',
      rollNo: '',
      class: 'Class 4(C)',
      fatherName: 'Piyush Khanna',
      dob: '06/18/2010',
      gender: 'Male',
      category: 'General',
      mobileNumber: '8895742310',
      localId: '',
      guardianPhone: '',
      address: '',
      photo: ''
    },
    {
      id: '18088',
      name: 'Andrew Donna',
      rollNo: '',
      class: 'Class 4(B)',
      fatherName: 'Kenneth Donna',
      dob: '06/17/2010',
      gender: 'Male',
      category: 'General',
      mobileNumber: '90676778564',
      localId: '',
      guardianPhone: '',
      address: '',
      photo: ''
    },
    {
      id: '18097',
      name: 'George Jeny Sharon',
      rollNo: '',
      class: 'Class 4(A)',
      fatherName: 'Eric Sharon',
      dob: '06/13/2014',
      gender: 'Male',
      category: 'General',
      mobileNumber: '09899789756',
      localId: '',
      guardianPhone: '',
      address: '',
      photo: ''
    },
    {
      id: '18099',
      name: 'Guru Rana',
      rollNo: '',
      class: 'Class 4(D)',
      fatherName: 'Nakul Rana',
      dob: '06/07/2022',
      gender: 'Male',
      category: 'General',
      mobileNumber: '8574693210',
      localId: '',
      guardianPhone: '',
      address: '',
      photo: ''
    },
    {
      id: '9000563',
      name: 'Cathrine Rosengren',
      rollNo: '521002',
      class: 'Class 4(C)',
      fatherName: 'Gagnon Rosengren',
      dob: '10/27/2010',
      gender: 'Male',
      category: 'General',
      mobileNumber: '899807543',
      localId: '',
      guardianPhone: '',
      address: '',
      photo: ''
    },
    {
      id: '90088',
      name: 'Jonathan Hibbins',
      rollNo: '8997',
      class: 'Class 4(A)',
      fatherName: 'Alexander',
      dob: '08/12/2006',
      gender: 'Male',
      category: 'General',
      mobileNumber: '890787680',
      localId: '',
      guardianPhone: '',
      address: '',
      photo: ''
    },
    {
      id: '911664',
      name: 'Henry Brown',
      rollNo: '54',
      class: 'Class 4(B)',
      fatherName: '',
      dob: '07/04/2018',
      gender: 'Male',
      category: 'General',
      mobileNumber: '9897919622',
      localId: '',
      guardianPhone: '',
      address: '',
      photo: ''
    },
    {
      id: '922259',
      name: 'Sophia Miller',
      rollNo: '63',
      class: 'Class 4(B)',
      fatherName: '',
      dob: '10/15/2017',
      gender: 'Female',
      category: '',
      mobileNumber: '9843514351',
      localId: '',
      guardianPhone: '',
      address: '',
      photo: ''
    }
  ];
  
  export default class4Data;
  