const class5Data = [
  {
    id: '07874',
    name: 'Scarlett Kennedy',
    rollNo: '30210',
    class: 'Class 5(A)',
    fatherName: 'David',
    dob: '03/05/2020',
    gender: 'Female',
    category: 'General',
    mobileNumber: '07778713673',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    balance: '543.00'
  },
  {
    id: '18001',
    name: 'Edward Thomas',
    rollNo: '101',
    class: 'Class 5(A)',
    fatherName: 'Olivier Thomas',
    dob: '03/11/2014',
    gender: 'Male',
    category: 'General',
    mobileNumber: '8233366611',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    balance: '0.00'
  },
  {
    id: '18002',
    name: 'Robin Peterson',
    rollNo: '102',
    class: 'Class 5(A)',
    fatherName: 'Lucas Peterson',
    dob: '07/12/2013',
    gender: 'Male',
    category: 'General',
    mobileNumber: '69898565464',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    balance: '128.00'
  },
  {
    id: '18004',
    name: 'Laura Clinton',
    rollNo: '109',
    class: 'Class 5(A)',
    fatherName: 'Michael Clinton',
    dob: '07/01/2015',
    gender: 'Female',
    category: 'General',
    mobileNumber: '65656546',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    balance: '0.00'
  },
  {
    id: '18005',
    name: 'Glen Stark',
    rollNo: '104',
    class: 'Class 5(B)',
    fatherName: 'James Stark',
    dob: '09/10/2015',
    gender: 'Male',
    category: 'General',
    mobileNumber: '9658471234',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    balance: '310.00'
  },
  {
    id: '18007',
    name: 'Brian Kohlar',
    rollNo: '107',
    class: 'Class 5(A)',
    fatherName: 'Nick Kohlar',
    dob: '01/05/2015',
    gender: 'Male',
    category: 'General',
    mobileNumber: '5646546546',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    balance: '89.00'
  },
  {
    id: '18010',
    name: 'Kriti Singh',
    rollNo: '111',
    class: 'Class 5(B)',
    fatherName: 'Manish Singh',
    dob: '06/17/2015',
    gender: 'Female',
    category: 'General',
    mobileNumber: '49456454',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    balance: '0.00'
  },
  {
    id: '18013',
    name: 'Benjamin Gates',
    rollNo: '113',
    class: 'Class 5(A)',
    fatherName: 'Nathan Gates',
    dob: '03/11/2016',
    gender: 'Male',
    category: 'General',
    mobileNumber: '4654646546',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    balance: '460.00'
  },
  {
    id: '18014',
    name: 'Devin Coinneach',
    rollNo: '4785',
    class: 'Class 5(A)',
    fatherName: 'jack Coinneach',
    dob: '06/25/2021',
    gender: 'Male',
    category: 'General',
    mobileNumber: '7411478552',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    balance: '0.00'
  },
  {
    id: '18016',
    name: 'Apolline',
    rollNo: '1243',
    class: 'Class 5(A)',
    fatherName: 'Elanie',
    dob: '02/16/2010',
    gender: 'Male',
    category: 'General',
    mobileNumber: '895412630',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    balance: '75.00'
  },
  {
    id: '18023',
    name: 'Karuna Rana',
    rollNo: '6541',
    class: 'Class 5(A)',
    fatherName: 'Rajesh Rana',
    dob: '06/16/2009',
    gender: 'Female',
    category: 'OBC',
    mobileNumber: '789654123',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    balance: '0.00'
  },
  {
    id: '18025',
    name: 'Jhonson wood',
    rollNo: '18004',
    class: 'Class 5(C)',
    fatherName: 'David',
    dob: '12/25/2010',
    gender: 'Male',
    category: 'General',
    mobileNumber: '76878567',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    balance: '341.00'
  },
  {
    id: '18029',
    name: 'Rahul Sinha',
    rollNo: '10',
    class: 'Class 5(B)',
    fatherName: 'G S SINHA',
    dob: '02/10/2010',
    gender: 'Male',
    category: 'General',
    mobileNumber: '8527413690',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    balance: '0.00'
  },
  {
    id: '18050',
    name: 'Kenal Dezzy',
    rollNo: '',
    class: 'Class 5(A)',
    fatherName: 'Rey Dezzy',
    dob: '03/29/2022',
    gender: 'Male',
    category: 'Physically Challenged',
    mobileNumber: '7748965525',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    balance: '234.00'
  },
  {
    id: '36220',
    name: 'Yash Sinha',
    rollNo: '23220',
    class: 'Class 5(C)',
    fatherName: 'Arjun',
    dob: '07/16/2015',
    gender: 'Male',
    category: 'General',
    mobileNumber: '90980678',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    balance: '0.00'
  },
  {
    id: '53322',
    name: 'Harry',
    rollNo: '',
    class: 'Class 5(C)',
    fatherName: 'kalvin',
    dob: '02/08/2023',
    gender: 'Male',
    category: '',
    mobileNumber: '',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    balance: '99.00'
  },
  {
    id: '90877',
    name: 'Vikash singh',
    rollNo: '9088887',
    class: 'Class 5(C)',
    fatherName: 'Gaurav singh',
    dob: '06/14/2013',
    gender: 'Male',
    category: 'General',
    mobileNumber: '9806787867',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    balance: '10.00'
  },
  {
    id: '908875',
    name: 'Saurabh Shah',
    rollNo: '2311',
    class: 'Class 5(A)',
    fatherName: 'Vinay Shah',
    dob: '07/17/2009',
    gender: 'Male',
    category: 'General',
    mobileNumber: '89078678',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    balance: '0.00'
  },
  {
    id: '980879',
    name: 'Markus Stones',
    rollNo: '',
    class: 'Class 5(B)',
    fatherName: 'Jonson Stones',
    dob: '11/15/2018',
    gender: 'Male',
    category: 'General',
    mobileNumber: '',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    balance: '188.00'
  }
];

export default class5Data;
