const filteredStudents = [
    {
      refNo: 588866,
      name: "Xavier Bartlett",
      className: "Class 1(A)",
      fatherName: "David Bartlett",
      dob: "05/13/2009",
      gender: "Male",
      formStatus: "Submitted (04/02/2025)",
      paymentStatus: "Paid",
      enrolled: false,
    },
    {
      refNo: 476039,
      name: "Nathan Smith",
      className: "Class 1(A)",
      fatherName: "Jason Smith",
      dob: "10/24/2013",
      gender: "Male",
      formStatus: "Submitted (03/31/2025)",
      paymentStatus: "Paid",
      enrolled: false,
    },
    {
      refNo: 433339,
      name: "Faran",
      className: "Class 3(A)",
      fatherName: "N/A",
      dob: "01/09/2024",
      gender: "Male",
      formStatus: "Submitted (03/01/2025)",
      paymentStatus: "Paid",
      enrolled: false,
    },
    {
      refNo: 673415,
      name: "Dev Malhotra",
      className: "Class 1(A)",
      fatherName: "Arjun",
      dob: "09/15/2017",
      gender: "Male",
      formStatus: "Not Submitted",
      paymentStatus: "Unpaid",
      enrolled: false,
    },
    {
      refNo: 383910,
      name: "Sophie Martin",
      className: "Class 5(A)",
      fatherName: "Kalvin Martin",
      dob: "06/22/2014",
      gender: "Female",
      formStatus: "Submitted (02/03/2025)",
      paymentStatus: "Paid",
      enrolled: false,
    },
    {
      refNo: 626618,
      name: "Jamie Overton",
      className: "Class 1(A)",
      fatherName: "Jason Overton",
      dob: "12/31/2018",
      gender: "Male",
      formStatus: "Not Submitted",
      paymentStatus: "Unpaid",
      enrolled: false,
    },
    {
      refNo: 376413,
      name: "Paul Walter",
      className: "Class 5(A)",
      fatherName: "Kalvin Walter",
      dob: "02/20/2018",
      gender: "Male",
      formStatus: "Submitted (01/03/2025)",
      paymentStatus: "Paid",
      enrolled: false,
    },
    {
      refNo: 518174,
      name: "Josh Philippe",
      className: "Class 1(A)",
      fatherName: "Marcus",
      dob: "08/21/2009",
      gender: "Male",
      formStatus: "Not Submitted",
      paymentStatus: "Unpaid",
      enrolled: false,
    },
    {
      refNo: 842727,
      name: "Jacob Bethell",
      className: "Class 1(A)",
      fatherName: "Brydon",
      dob: "08/19/2016",
      gender: "Male",
      formStatus: "Submitted (12/03/2024)",
      paymentStatus: "Paid",
      enrolled: false,
    },
    {
      refNo: 117923,
      name: "Ryan Burl",
      className: "Class 2(D)",
      fatherName: "Dion Myers",
      dob: "05/13/1999",
      gender: "Male",
      formStatus: "Not Submitted",
      paymentStatus: "Unpaid",
      enrolled: false,
    },
    {
      refNo: 375789,
      name: "Arun Sinha",
      className: "Class 5(A)",
      fatherName: "Vinay Sinha",
      dob: "06/20/2013",
      gender: "Male",
      formStatus: "Submitted (11/05/2024)",
      paymentStatus: "Paid",
      enrolled: false,
    },
    {
      refNo: 812845,
      name: "Olia Watson",
      className: "Class 3(A)",
      fatherName: "Methews",
      dob: "11/25/1999",
      gender: "Female",
      formStatus: "Not Submitted",
      paymentStatus: "Unpaid",
      enrolled: false,
    },
    {
      refNo: 118997,
      name: "Ayan Desai",
      className: "Class 1(A)",
      fatherName: "Abhinand",
      dob: "10/15/2015",
      gender: "Male",
      formStatus: "Submitted (10/01/2024)",
      paymentStatus: "Paid",
      enrolled: false,
    },
    {
      refNo: 570577,
      name: "Abhishek Paradkar",
      className: "Class 2(A)",
      fatherName: "Utkarsh Paradkar",
      dob: "07/19/2013",
      gender: "Male",
      formStatus: "Not Submitted",
      paymentStatus: "Unpaid",
      enrolled: false,
    },
    {
      refNo: 774598,
      name: "Sivarajan Solaimalai",
      className: "Class 5(A)",
      fatherName: "Sukant",
      dob: "12/15/2005",
      gender: "Male",
      formStatus: "Not Submitted",
      paymentStatus: "Unpaid",
      enrolled: false,
    },
    {
      refNo: 881781,
      name: "Cathrine Rosengren",
      className: "Class 3(A)",
      fatherName: "Gagnon Rosengren",
      dob: "10/27/2010",
      gender: "Male",
      formStatus: "Submitted (09/02/2024)",
      paymentStatus: "Paid",
      enrolled: false,
    },
    {
      refNo: 640769,
      name: "Jennifer Ford",
      className: "Class 2(A)",
      fatherName: "Gregory Ford",
      dob: "07/06/2007",
      gender: "Female",
      formStatus: "Not Submitted",
      paymentStatus: "Unpaid",
      enrolled: false,
    },
    {
      refNo: 717223,
      name: "Jonathan Hibbins",
      className: "Class 3(A)",
      fatherName: "Alexander",
      dob: "08/12/2006",
      gender: "Male",
      formStatus: "Submitted (08/02/2024)",
      paymentStatus: "Paid",
      enrolled: false,
    }
  ];
  
  export default filteredStudents;
  