import Header from "./header";
import Sidebar from "./sidebar/layout";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "DLT - Admin Panel",
  description: "Generated by create next app",
};

export default function DLTPage({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="light">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="DLT admin is super flexible, powerful, clean & modern responsive tailwind Admin Panel with unlimited possibilities." />
        <meta name="keywords" content="Admin Panel, DLT Admin Panel, dashboard template, flat Admin Panel, responsive Admin Panel, web app" />
        <meta name="author" content="LEFT4CODE" />
        <link rel="stylesheet" href="/dist/css/app.css" />
      </head>
      <body className="py-5 md:py-0">
        <div>
          <Header />
          <div className="flex overflow-hidden">
            <Sidebar />
            <main
              className="content w-full md:ml-64"
              style={{ minHeight: "calc(100vh - 65px)" }}
            >
              {children}
            </main>
          </div>
          <div
            data-url="/dark-mode"
            className="dark-mode-switcher cursor-pointer shadow-md fixed bottom-0 right-0 box dark:bg-dark-2 border rounded-full w-40 h-12 flex items-center justify-center z-50 mb-10 mr-10"
          >
            <div className="mr-4 text-gray-700 dark:text-gray-300">Dark Mode</div>
            <div className="dark-mode-switcher__toggle border"></div>
          </div>
        </div>
      </body>
    </html>
  );
}
