// src/app/layout.tsx
import '../app/globals.css';
import type { Metadata } from 'next';
import Header from './header';
import Sidebar from './sidebar/layout';

export const metadata: Metadata = {
  title: 'Enigma - Admin Template',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div style={{ display: 'flex', marginTop: '65px' }}>
          <Sidebar />
          <main style={{ marginLeft: '250px', padding: '20px', width: '100%' }}>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}