import "../app/globals.css";
import type { Metadata } from "next";
import Header from "./header";
import Sidebar from "./sidebar/layout"; // Adjust path if needed

export const metadata: Metadata = {
  title: "Enigma - Admin Template",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div style={{ display: "flex" }}>
          <Sidebar />
          <main style={{ padding: "20px", width: "100%", marginLeft: "250px" }}>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}