const profileFields = [
    { id: 1, name: 'First Name', enabled: true },
    { id: 2, name: 'Admission Date', enabled: true },
    { id: 3, name: 'Last Name', enabled: true },
    { id: 4, name: 'RTE', enabled: true },
    { id: 5, name: 'Student Photo', enabled: true },
    { id: 6, name: 'Mobile Number', enabled: true },
    { id: 7, name: 'Email', enabled: true },
    { id: 8, name: 'Religion', enabled: true },
    { id: 9, name: 'Caste', enabled: true },
    { id: 10, name: 'Date of Birth', enabled: true },
    { id: 11, name: 'Blood Group', enabled: true },
    { id: 12, name: 'If Guardian Is', enabled: true },
    { id: 13, name: 'Gender', enabled: true },
    { id: 14, name: 'Current Address', enabled: true },
    { id: 15, name: 'Permanent Address', enabled: true },
    { id: 16, name: 'Category', enabled: true },
    { id: 17, name: 'Bank Account Number', enabled: true },
    { id: 18, name: 'Bank Name', enabled: true },
    { id: 19, name: 'IFSC Code', enabled: true },
    { id: 20, name: 'Father Name', enabled: true },
    { id: 21, name: 'Father Phone', enabled: true },
    { id: 22, name: 'Father Occupation', enabled: true },
    { id: 23, name: 'Mother Name', enabled: true },
    { id: 24, name: 'Mother Phone', enabled: true },
    { id: 25, name: 'House', enabled: true },
    { id: 26, name: 'Mother Occupation', enabled: true },
    { id: 27, name: 'Guardian Name', enabled: true },
    { id: 28, name: 'Guardian Relation', enabled: true },
    { id: 29, name: 'Guardian Phone', enabled: true },
    { id: 30, name: 'Guardian Occupation', enabled: true },
    { id: 31, name: 'Guardian Address', enabled: true },
    { id: 32, name: 'Guardian Email', enabled: true },
    { id: 33, name: 'National Identification Number', enabled: true },
    { id: 34, name: 'Local Identification Number', enabled: true },
    { id: 35, name: 'Father Photo', enabled: true },
    { id: 36, name: 'Mother Photo', enabled: true },
    { id: 37, name: 'Guardian Photo', enabled: true },
    { id: 38, name: 'Height', enabled: true },
    { id: 39, name: 'Weight', enabled: true },
    { id: 40, name: 'Previous School Details', enabled: true },
    { id: 41, name: 'Medical History', enabled: true }
  ];
  
export default profileFields;
  