const parentsData = [
        { "Guardian Name": "Lyndon", "Guardian Phone": "1680848101", "Username": "parent82", "Action": false },
        { "Guardian Name": "Abhinand", "Guardian Phone": "7890789675", "Username": "parent90", "Action": false },
        { "Guardian Name": "Brydon", "Guardian Phone": "90906786", "Username": "parent92", "Action": false },
        { "Guardian Name": "Philip", "Guardian Phone": "996857412", "Username": "parent34", "Action": false },
        { "Guardian Name": "Lokesh", "Guardian Phone": "089068797", "Username": "parent59", "Action": false },
        { "Guardian Name": "arun singh", "Guardian Phone": "908079678", "Username": "parent83", "Action": false },
        { "Guardian Name": "Martin", "Guardian Phone": "08965655", "Username": "parent86", "Action": false },
        { "Guardian Name": "Kalwin", "Guardian Phone": "0896878688", "Username": "parent95", "Action": false },
        { "Guardian Name": "Glenn Heart", "Guardian Phone": "645646544", "Username": "parent8", "Action": false },
        { "Guardian Name": "James Stark", "Guardian Phone": "54646546", "Username": "parent4", "Action": false },
        { "Guardian Name": "Ravi Raina", "Guardian Phone": "8854712369", "Username": "parent26", "Action": false },
        { "Guardian Name": "Eric Sharon", "Guardian Phone": "7859412582", "Username": "parent33", "Action": false },
        { "Guardian Name": "KP RAJPUT", "Guardian Phone": "9212121214", "Username": "parent42", "Action": false },
        { "Guardian Name": "sumita soni", "Guardian Phone": "9546546421", "Username": "parent53", "Action": false },
        { "Guardian Name": "Alexander", "Guardian Phone": "980678678", "Username": "parent88", "Action": false },
        { "Guardian Name": "Gagnon Rosengren", "Guardian Phone": "890868678", "Username": "parent89", "Action": false },
        { "Guardian Name": "Olivier Thomas", "Guardian Phone": "98654646", "Username": "parent9", "Action": false },
        { "Guardian Name": "Lucas Peterson", "Guardian Phone": "946545445", "Username": "parent2", "Action": false },
        { "Guardian Name": "Nick Kohlar", "Guardian Phone": "946545445", "Username": "parent6", "Action": false },
        { "Guardian Name": "Michael Clinton", "Guardian Phone": "544545454", "Username": "parent7", "Action": false },
        { "Guardian Name": "Nathan Gates", "Guardian Phone": "6465465465", "Username": "parent10", "Action": false },
        { "Guardian Name": "Elanie", "Guardian Phone": "0223585252", "Username": "parent15", "Action": false },
        { "Guardian Name": "Rajesh Rana", "Guardian Phone": "7412589630", "Username": "parent17", "Action": false },
        { "Guardian Name": "jack Coinneach", "Guardian Phone": "7896541230", "Username": "parent18", "Action": false },
        { "Guardian Name": "David", "Guardian Phone": "8776889879", "Username": "parent23", "Action": false },
        { "Guardian Name": "Rey Dezzy", "Guardian Phone": "789325410", "Username": "parent36", "Action": false },
        { "Guardian Name": "Vinay Shah", "Guardian Phone": "089078675", "Username": "parent47", "Action": false },
        { "Guardian Name": "kalvin", "Guardian Phone": "89089067868", "Username": "parent51", "Action": false },
        { "Guardian Name": "Gaurav singh", "Guardian Phone": "8909806786", "Username": "parent52", "Action": false },
        { "Guardian Name": "David", "Guardian Phone": "07778713673", "Username": "parent71", "Action": false },
        { "Guardian Name": "Arjun", "Guardian Phone": "8907687686", "Username": "parent74", "Action": false },
        { "Guardian Name": "Manish Singh", "Guardian Phone": "165465415", "Username": "parent11", "Action": false },
        { "Guardian Name": "Rishab", "Guardian Phone": "6985471230", "Username": "parent20", "Action": false },
        { "Guardian Name": "Jonson Stones", "Guardian Phone": "", "Username": "parent69", "Action": false },
        { "Guardian Name": "Paul", "Guardian Phone": "67878878", "Username": "parent24", "Action": false },
        { "Guardian Name": "Kenneth Donna", "Guardian Phone": "635855245", "Username": "parent32", "Action": false },
        { "Guardian Name": "James", "Guardian Phone": "9897919622", "Username": "parent43", "Action": false },
        { "Guardian Name": "Lucas", "Guardian Phone": "9843514351", "Username": "parent44", "Action": false },
        { "Guardian Name": "Tarun sinha", "Guardian Phone": "7418529630", "Username": "parent19", "Action": false },
        { "Guardian Name": "Piyush Khanna", "Guardian Phone": "8854793210", "Username": "parent31", "Action": false },
        { "Guardian Name": "Nakul Rana", "Guardian Phone": "789541230", "Username": "parent37", "Action": false },
        { "Guardian Name": "gauri", "Guardian Phone": "soni", "Username": "parent54", "Action": false },
        { "Guardian Name": "BIMLESH SINGH", "Guardian Phone": "678567567658", "Username": "parent35", "Action": false },
        { "Guardian Name": "Arun", "Guardian Phone": "849401561", "Username": "parent58", "Action": false },
        { "Guardian Name": "Arjun sharma", "Guardian Phone": "679078979", "Username": "parent73", "Action": false },
        { "Guardian Name": "Medison", "Guardian Phone": "21841041840", "Username": "parent79", "Action": false },
        { "Guardian Name": "Lister", "Guardian Phone": "490848430", "Username": "parent80", "Action": false },
        { "Guardian Name": "Suresh", "Guardian Phone": "906786785", "Username": "parent85", "Action": false },
        { "Guardian Name": "Arjun Kumar", "Guardian Phone": "789678456", "Username": "parent96", "Action": false },
        { "Guardian Name": "Jayant Sindhu", "Guardian Phone": "890678564", "Username": "parent97", "Action": false },
        { "Guardian Name": "Jason Smith", "Guardian Phone": "8905754623", "Username": "parent98", "Action": false },
        { "Guardian Name": "David bartlett", "Guardian Phone": "090788776", "Username": "parent99", "Action": false }
      ];
      
export default parentsData;