const class3Data = [
  {
    id: '0202',
    name: 'Emma Thomas',
    rollNo: '2150',
    class: 'Class 3(B)',
    fatherName: 'Olivier Thomas',
    dob: '07/14/2016',
    gender: 'Female',
    category: 'General',
    mobileNumber: '6881016512',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    status: false
  },
  {
    id: '03321',
    name: 'John M. Pinto',
    rollNo: '20056',
    class: 'Class 3(A)',
    fatherName: 'Martin',
    dob: '01/12/2009',
    gender: 'Male',
    category: 'OBC',
    mobileNumber: '8906786784',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    status: false
  },
  {
    id: '12003',
    name: 'Jasaon Martin',
    rollNo: '250011',
    class: 'Class 3(A)',
    fatherName: 'Kalwin',
    dob: '09/19/2013',
    gender: 'Male',
    category: 'General',
    mobileNumber: '8906787573',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    status: false
  },
  {
    id: '18077',
    name: 'Dharambir Singh',
    rollNo: '',
    class: 'Class 3(B)',
    fatherName: 'Bimlesh',
    dob: '02/11/2020',
    gender: 'Male',
    category: 'General',
    mobileNumber: '852522872525',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    status: false
  },
  {
    id: '18078',
    name: 'Alexander Kayla',
    rollNo: '',
    class: 'Class 3(A)',
    fatherName: 'Philip',
    dob: '05/13/2009',
    gender: 'Male',
    category: '',
    mobileNumber: '8854114725',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    status: false
  },
  {
    id: '326260',
    name: 'Arpit Patel',
    rollNo: '20230',
    class: 'Class 3(C)',
    fatherName: 'Arun Patel',
    dob: '07/16/2010',
    gender: 'Male',
    category: 'OBC',
    mobileNumber: '95447744551',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    status: false
  },
  {
    id: '90775',
    name: 'Suresh Patel',
    rollNo: '4322',
    class: 'Class 3(A)',
    fatherName: 'Lokesh',
    dob: '07/19/2014',
    gender: 'Male',
    category: 'General',
    mobileNumber: '9080678678',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    status: false
  },
  {
    id: '90957',
    name: 'Shalini sharma',
    rollNo: '20032',
    class: 'Class 3(D)',
    fatherName: 'Arjun sharma',
    dob: '12/30/2008',
    gender: 'Female',
    category: 'General',
    mobileNumber: '890890678',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    status: false
  }
];

export default class3Data;
