const class2Data = [
  {
    id: '980867',
    name: 'Vinni Khatri',
    rollNo: '32600',
    class: 'Class 2(B)',
    fatherName: 'Suresh',
    dob: '01/07/2019',
    gender: 'Female',
    category: 'General',
    mobileNumber: '89089795',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    status: false
  },
  {
    id: '96302',
    name: 'Jacob Bethell',
    rollNo: '221002',
    class: 'Class 2(A)',
    fatherName: 'Brydon',
    dob: '08/19/2016',
    gender: 'Male',
    category: 'General',
    mobileNumber: '065758878',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    status: false
  },
  {
    id: '5482',
    name: 'Mayer',
    rollNo: '0202',
    class: 'Class 2(B)',
    fatherName: 'Medison',
    dob: '06/13/2019',
    gender: 'Male',
    category: '',
    mobileNumber: '5360648401',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    status: false
  },
  {
    id: '2152',
    name: 'Kaylen',
    rollNo: '0205',
    class: 'Class 2(A)',
    fatherName: 'Lyndon',
    dob: '06/19/2019',
    gender: 'Female',
    category: '',
    mobileNumber: '54180185420',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    status: false
  },
  {
    id: '1205',
    name: 'Hazel',
    rollNo: '0203',
    class: 'Class 2(B)',
    fatherName: 'Lister',
    dob: '06/19/2019',
    gender: 'Female',
    category: '',
    mobileNumber: '6595048420',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    status: false
  },
  {
    id: '120036',
    name: 'Ayan Desai',
    rollNo: '23620',
    class: 'Class 2(A)',
    fatherName: 'Abhinand',
    dob: '10/15/2015',
    gender: 'Male',
    category: 'General',
    mobileNumber: '9067875674',
    localId: '',
    guardianPhone: '',
    address: '',
    photo: '',
    status: false
  }
];

export default class2Data;
